import { Inter } from "next/font/google";
<<<<<<< HEAD
import Sidebar from './components/Sidebar';
import { CssBaseline } from '@mui/material';
import Box from '@mui/material/Box';
=======
import "./globals.css";
>>>>>>> 591627a71416a913a67a02b87c03a4aa84c9606c

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "Pantry Tracker",
  description: "Manage your pantry efficiently",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 591627a71416a913a67a02b87c03a4aa84c9606c
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={inter.className}>
        <CssBaseline />
        <Box sx={{ display: 'flex' }}>
          <Sidebar />
          <Box
            component="main"
            width="100%"
            sx={{ backgroundColor: 'white' }}
          >
            {children}
          </Box>
        </Box>
      </body>
=======
      <body className={inter.className}>{children}</body>
>>>>>>> 591627a71416a913a67a02b87c03a4aa84c9606c
    </html>
  );
}
